In [3]:
import pandas as pd
import numpy as np
import re

In [4]:
for_sale = pd.read_csv('chicago_for_sale_unclean.csv')
sold = pd.read_csv('chicago_sold_unclean.csv')

In [5]:
df = pd.concat([for_sale, sold]).drop(columns=['Unnamed: 0']).reset_index()
df.head(5)

,index,Type,Year built,Heating,Cooling,Parking,Price/sqft,Total Price,Address,New construction,Bedrooms,Bathrooms,Full bathrooms,neighborhood_stats,URL,Lot,Square Feet,HOA,Half bathrooms,Status
0,0,Multi Family,1921,Forced air,No Data,2 spaces,No Data,"$279,900","5931 S Campbell Ave, Chicago, IL 60629",No,6,3.0,3.0,Home values in Chicago Lawn have risen 0.6% ()...,https://www.zillow.com/homedetails/5931-S-Camp...,NaN,NaN,NaN,NaN,For Sale
1,1,Single Family,1924,Gas,Central,2 spaces,$141,"$138,970","11117 S Sawyer Ave, Chicago, IL 60655",No,3,1.0,1.0,Home values in Mount Greenwood have risen 0.6%...,https://www.zillow.com/homedetails/11117-S-Saw...,"3,789 sqft",988,NaN,NaN,For Sale
2,2,Multi Family,1930,Forced air,No Data,None,No Data,"$99,900","7151 S Green St, Chicago, IL 60621",No,6,2.0,2.0,Home values in Englewood have risen 0.6% () ov...,https://www.zillow.com/homedetails/7151-S-Gree...,NaN,NaN,NaN,NaN,For Sale
3,3,Single Family,1898,Gas,No Data,1 space,$27,"$39,900","620 W 60th St, Chicago, IL 60621",No,4,2.0,2.0,Home values in Englewood have risen 0.6% () ov...,https://www.zillow.com/homedetails/620-W-60th-...,"3,301 sqft","1,498",None,NaN,For Sale
4,4,Condo,1934,Forced air,No Data,None,$169,"$168,900","5148 N Monitor Ave APT 202, Chicago, IL 60630",No,2,1.0,1.0,Home values in Jefferson Park have risen 0.6% ...,https://www.zillow.com/homedetails/5148-N-Moni...,NaN,"1,000",$234/month,NaN,For Sale

In [16]:
# there are a few duplicate urls so we will drop those
df.drop_duplicates(subset=['URL'], inplace=True)

In [17]:
df.replace(to_replace=['None', 'No Data'], value=np.nan, inplace=True)

In [18]:
def acres_to_sqft(x):
    if isinstance(x, list):
        if 'acres' in x:
            sqft = float(x[0]) * 43560
            return round(sqft, 2)
        else:
            return float(x[0].replace(',',''))
    else:
        return x
    

df['Total Price'] = df['Total Price'].apply(lambda x: float(re.sub("[^0-9]", "", x)) if isinstance(x, str) else x)
df['HOA'] = df['HOA'].apply(lambda x: float(re.sub("[^0-9]", "", x)) if isinstance(x, str) else x)
df['Bedrooms'] = df['Bedrooms'].apply(lambda x: float(re.sub("[^0-9]", "", x)) if isinstance(x, str) else x)
df['Bathrooms'] = df['Bathrooms'].apply(lambda x: float(re.sub("[^0-9]", "", x)) if isinstance(x, str) else x)
df['Square Feet'] = df['Square Feet'].apply(lambda x: float(re.sub("[^0-9]", "", x)) if isinstance(x, str) else x)
df['Full bathrooms'] = df['Full bathrooms'].apply(lambda x: int(x) if isinstance(x, str) else x)
df['Half bathrooms'].fillna(0, inplace=True)
df['Half bathrooms'] = df['Half bathrooms'].astype(int)
df['Year built'] = df['Year built'].apply(lambda x: int(x) if isinstance(x, str) else x)
df['Cooling'] = df.Cooling.replace('Refrigerator', 'Refrigeration')
df.Cooling.fillna('None', inplace=True)
df['Lot'] = df['Lot'].apply(lambda x: x.lower() if isinstance(x, str) else x)
df['Lot Temp'] = df['Lot'].str.split(' ')
df['Lot'] = df['Lot Temp'].apply(acres_to_sqft)
df.drop(columns=['Lot Temp', 'Price/sqft', 'index'], inplace=True)

In [19]:
pwd

'/Users/collinswestnedge/programming/Metis_Online/project_02'

In [23]:
df.dtypes

Type                   object
Year built            float64
Heating                object
Cooling                object
Parking                object
Total Price           float64
Address                object
New construction       object
Bedrooms                int64
Bathrooms             float64
Full bathrooms        float64
neighborhood_stats     object
URL                    object
Lot                   float64
Square Feet           float64
HOA                   float64
Half bathrooms          int64
Status                 object
dtype: object

In [27]:
for item in df.columns.to_list():
    print(item + ':')
    print(df[item].value_counts())
    print()

Type:
Condo                 557
Single Family         324
Multi Family           91
Multiple Occupancy     53
Townhouse              43
Apartment               1
Name: Type, dtype: int64

Year built:
2020.0    31
1920.0    31
2007.0    27
2008.0    27
2006.0    26
          ..
1870.0     1
1936.0     1
1869.0     1
1884.0     1
1896.0     1
Name: Year built, Length: 141, dtype: int64

Heating:
Forced air                         461
Gas                                221
Forced air, Gas                    186
Other                               28
Baseboard                           22
Electric                            20
Radiant                              9
Electric, Gas                        8
Forced air, Electric                 8
Other, Gas                           8
Baseboard, Forced air                5
Heat pump                            4
Forced air, Other                    3
Forced air, Electric, Gas            3
Radiant, Gas                         3
Baseboard, Gas                       3
Baseboard, Electric                  3
Forced air, Heat pump                2
Baseboard, Radiant, Gas              2
Other, Radiant                       1
Gas, Other                           1
Baseboard, Radiant                   1
Radiant, Electric                    1
Baseboard, Forced air, Gas           1
Forced air, Heat pump, Electric      1
Wall, Electric                       1
Baseboard, Gas, Other                1
Forced air, Radiant                  1
Name: Heating, dtype: int64

Cooling:
Central           786
None              238
Other              19
Wall               17
Refrigeration       7
Central, Other      2
Name: Cooling, dtype: int64

Parking:
1 space            443
2 spaces           396
3 spaces            22
4 spaces            20
6 spaces             8
Attached Garage      8
5 spaces             5
42 spaces            5
On street            2
7 spaces             2
Detached Garage      1
8 spaces             1
15 spaces            1
Name: Parking, dtype: int64

Total Price:
275000.0    10
315000.0    10
375000.0    10
475000.0     9
225000.0     9
            ..
404000.0     1
123500.0     1
336500.0     1
397900.0     1
1900.0       1
Name: Total Price, Length: 527, dtype: int64

Address:
(Undisclosed Address), Chicago, IL 60628         2
6906 N Ashland Blvd #GS, Chicago, IL 60626       2
2869 W Lyndale St UNIT 2, Chicago, IL 60647      2
5124 N Melvina Ave, Chicago, IL 60630            1
7762 W North Shore Ave, Chicago, IL 60631        1
                                                ..
1006 W Cullerton St #1, Chicago, IL 60608        1
1070 W 15th St UNIT 303, Chicago, IL 60608       1
2351 W Congress Pkwy APT 1, Chicago, IL 60612    1
2251 W Cullerton St, Chicago, IL 60608           1
510 W 75th St, Chicago, IL 60621                 1
Name: Address, Length: 1066, dtype: int64

New construction:
 No     1034
 Yes      35
Name: New construction, dtype: int64

Bedrooms:
2     274
3     272
4     172
1     136
5      92
6      48
7      22
0      22
8      12
9      10
11      5
10      3
12      1
Name: Bedrooms, dtype: int64

Bathrooms:
2.0     459
1.0     242
3.0     228
4.0      80
5.0      32
6.0      16
7.0       3
8.0       2
11.0      1
Name: Bathrooms, dtype: int64

Full bathrooms:
2.0    489
1.0    300
3.0    194
4.0     30
5.0     20
6.0     10
7.0      1
8.0      1
Name: Full bathrooms, dtype: int64

neighborhood_stats:
Home values in Englewood have risen 0.6% () over the past 12 months.Zillow predicts the home values in Englewood will increase 9% () in the next year.This home is valued 104.9% higher () than the median home in Englewood.The median Zestimate for this neighborhood is $48,744.                  3
Home values in Rogers Park have risen 0.6 % (↑) over the past 12 months.Zillow predicts the home values in Rogers Park will increase 1.4% (↑) in the next year.This home is valued 28.8% lower (↓) than the median home in Rogers Park.The median Zestimate® for this neighborhood is $226,102.      2
Home values in Roseland have risen 0.6% () over the past 12 months.Zillow predicts the home values in Roseland will rise 3.9% () in the next year.This home is valued 15.5% higher () than the median home in Roseland.The median Zestimate for this neighborhood is $83,973.                        2
Home values in Logan Square have risen 0.6 % (↑) over the past 12 months.Zillow predicts the home values in Logan Square will increase 1.6% (↑) in the next year.This home is valued 40% higher (↑) than the median home in Logan Square.The median Zestimate® for this neighborhood is $403,670.    2
Home values in Logan Square have risen 0.6% () over the past 12 months.Zillow predicts the home values in Logan Square will increase 1.6% () in the next year.This home is valued 1.2% lower () than the median home in Logan Square.The median Zestimate for this neighborhood is $403,670.         2
                                                                                                                                                                                                                                                                                                    ..
Home values in Beverly have risen 0.6% () over the past 12 months.Zillow predicts the home values in Beverly will rise 0.8% () in the next year.This home is valued 15.2% higher () than the median home in Beverly.The median Zestimate for this neighborhood is $346,385.                          1
Home values in Sauganash have risen 0.6 % (↑) over the past 12 months.Zillow predicts the home values in Sauganash will rise 1.5% (↑) in the next year.This home is valued 40.9% higher (↑) than the median home in Sauganash.The median Zestimate® for this neighborhood is $436,778.               1
Home values in South Loop have risen 0.6% () over the past 12 months.Zillow predicts the home values in South Loop will increase 3.2% () in the next year.This home is valued 43.2% lower () than the median home in South Loop.The median Zestimate for this neighborhood is $376,901.              1
Home values in The Loop have risen 0.6 % (↑) over the past 12 months.Zillow predicts the home values in The Loop will fall 3.3% (↓) in the next year.This home is valued 57.1% higher (↑) than the median home in The Loop.The median Zestimate® for this neighborhood is $369,141.                  1
Home values in Bucktown have risen 0.6% () over the past 12 months.Zillow predicts the home values in Bucktown will rise 0.5% () in the next year.This home is valued 25.3% lower () than the median home in Bucktown.The median Zestimate for this neighborhood is $601,188.                        1
Name: neighborhood_stats, Length: 1054, dtype: int64

URL:
https://www.zillow.com/homedetails/1918-S-Hamlin-Ave-Chicago-IL-60623/2080547737_zpid/            1
https://www.zillow.com/homedetails/432-E-89th-St-Chicago-IL-60619/4116130_zpid/                   1
https://www.zillow.com/homedetails/60-E-Scott-St-APT-403-Chicago-IL-60610/3845032_zpid/           1
https://www.zillow.com/homedetails/1617-W-Barry-Ave-APT-1W-Chicago-IL-60657/65561830_zpid/        1
https://www.zillow.com/homedetails/1426-W-Cullom-Ave-APT-1-Chicago-IL-60613/65559234_zpid/        1
                                                                                                 ..
https://www.zillow.com/homedetails/6958-N-Tonty-Ave-Chicago-IL-60646/3553382_zpid/                1
https://www.zillow.com/homedetails/2103-N-Campbell-Ave-APT-1S-Chicago-IL-60647/123561167_zpid/    1
https://www.zillow.com/homedetails/720-W-Gordon-Ter-APT-20L-Chicago-IL-60613/3704522_zpid/        1
https://www.zillow.com/homedetails/1231-W-Fletcher-St-UNIT-G-Chicago-IL-60657/3727292_zpid/       1
https://www.zillow.com/homedetails/1300-W-Altgeld-St-118-Chicago-IL-60614/3729695_zpid/           1
Name: URL, Length: 1069, dtype: int64

Lot:
3750.0    19
3123.0    16
3746.0    10
3136.0     9
3781.0     7
          ..
4720.0     1
4064.0     1
3576.0     1
4000.0     1
2781.0     1
Name: Lot, Length: 206, dtype: int64

Square Feet:
1200.0    48
1000.0    30
1500.0    29
1300.0    24
1100.0    20
          ..
1110.0     1
1030.0     1
2685.0     1
1691.0     1
988.0      1
Name: Square Feet, Length: 403, dtype: int64

HOA:
150.0    10
300.0    10
250.0     6
375.0     6
200.0     6
         ..
412.0     1
636.0     1
134.0     1
444.0     1
389.0     1
Name: HOA, Length: 392, dtype: int64

Half bathrooms:
0    817
1    236
2     11
3      5
Name: Half bathrooms, dtype: int64

Status:
For Sale    779
Sold        290
Name: Status, dtype: int64

In [28]:
df.to_csv('/Users/collinswestnedge/programming/Metis_Online/project_02/clean_data/chicago_full_clean.csv')